### ISSUE TITLE
Is it needed to update thingsboard.version parameter in POM file every TB upgrade?

### ISSUE THREAD

**Issue by alexcorvis84** [thingsboard/rule-node-examples#18]
I had developed a few custom nodes that were working version **3.3.4**

Now, I've updated Thingsboard platform to the latest version **3.5.0**, but everytime I try to use a custom node, I receive errors (in method OnStart) when I try to use any of them.

I'm using Thingsboard version deployed as a cluster (with docker-compose) with a shared volume pointing to **/usr/share/thingsboard/extensions** (for tb-core1 & tb-core2) containing the custom nodes ***.jar** files.

```
java.lang.ClassNotFoundException: com.grupotsk.iot.rule.engine.node.external.MQTTPublisherNode
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:171)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:64)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:65)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$tryInit$1(TbActorMailbox.java:82)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I'm wondering if it is **mandatory** to update **thingsboard.version** parameter in **POM** file and recompile custom nodes code everytime the platform is upgraded? are not backward compatible with major versions? What can be the error if not?

Thank in advance!

**Comment by smatvienko-tb** [comment]
Hi, @alexcorvis84!

The best practice is to build custom rule nodes for each version of the ThingsBoard. You should update
`thingsboard.version` to the current that you are using.
For the minor updates, you probably did not notice any changes (3.3.3 -> 3.3.4). 
For significant updates may need to update custom rule nodes because some interfaces or classes may change (3.3.4 -> 3.5.0)

My daily basis approach to managing my custom nodes with containers is to build my custom image from the standard.

Here you can find my example of [Dockerfile](https://github.com/thingsboard/rule-node-examples/blob/master/Dockerfile) and updated [README](https://github.com/thingsboard/rule-node-examples/tree/master).

This will help you and the community to maintain custom rule nodes much more straightforward.

**Comment by smatvienko-tb** [comment]
Hi, @alexcorvis84!

The `PLUGINS_SCAN_PACKAGES` implementation is simple and has not changed for a long time. And I see no problem with the values you provided.
Please, make sure that your `rule-engine-1.0.0-custom-nodes.jar` contains the class you are looking for (check the jar file content)

Also, please build the jar with the latest ThingsBoard version.
Without rebuilding, your custom class may depend on some 3rd party classes that no longer exist in the ThingsBoard.

In my practice, I use the same package provided by this project with my client subfolder
like `package org.thingsboard.rule.engine.node.vipclient;`

**Comment by alexcorvis84** [comment]
Hi @smatvienko-tb 

Thanks for the heads up.

**Comment by alexcorvis84** [comment]
Hi @smatvienko-tb 

Just to confirm, 

Which services should contain the *.jar files? **All** the **replicas** of **tb-core** and **tb-rule-engine**?
